version: '3.9'

services: 
    db:
        image: 'postgres'
        ports: 
            - '4444:5432'
        environment: 
            POSTGRES_USER: 'dbuser'
            POSTGRES_PASSWORD: '1234' 
    server: 
        # image: 'pyrenthesis/rectangle-storage'
        build: . # TODO: Remove this
        ports:
            - '3000:3000'
        depends_on:
            - "db"
